function trained_autoenc=train_sparse(hiddenSize,lambda,sparsity_target)
load('~/data_MNIST_MATLAB/train1mat.mat');
X=train1mat;
trained_autoenc=trainAutoencoder(X,hiddenSize,...
    'MaxEpochs',20,...
    'L2WeightRegularization',0,...
    'ShowProgressWindow',false,...
    'SparsityProportion',sparsity_target,...
    'SparsityRegularization',lambda);
end